### ISSUE TITLE
Error when installing OSLO

### ISSUE THREAD

**Issue by josemlopez** [EleutherAI/oslo#10]
## How to reproduce

```python 
python setup.py install
```

## Environment

- OS : CentOS 7.9
- Python version : 3.9
- Transformers version : 4.21.2
- Whether to use Docker:
- Misc.:

```
# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 18, in <module>
    long_description=open("README.md").read(),
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```

Solution applied in my local: include a README.md

**Comment by hyunwoongko** [comment]
Fixed by https://github.com/EleutherAI/oslo/pull/16
