### ISSUE TITLE
No _TensorParallelMappingForHuggingFace 

### ISSUE THREAD

**Issue by dongsungkim** [EleutherAI/oslo#88]
## How to reproduce

```python 
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nnodes=1 --nproc_per_node=2  ./tests/torch/nn/parallel/data_parallel/test_ddp.py
```
The bus comes from latest submission which changes _TensorParallelMappingForHuggingFace to _ParallelMapping. It happens when parallel_context is called. (tensor_parallel import issue)

## Environment

- OS : 18.04
- Python version : 3.7
- Transformers version : 4.21.2
- Whether to use Docker:
- Misc.:

**Comment by hyunwoongko** [comment]
cc @loopinf
